version: "3"

services:
  backend:
    build: .
    ports:
      - "3000:8080"
    privileged: false
    environment:
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - DEPLOYED_DOMAIN=${DEPLOYED_DOMAIN}

  
  db:
    build: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=snh
    privileged: false
   
